FROM ghcr.io/zitadel/zitadel:v4.11.0@sha256:74bdb4f9a806cced80677d34c548e46f48dac03bd4835a198e7db5bb1ac33884

# Copy configuration and certificates
COPY --chown=zitadel:zitadel ./*.yaml ./certificate.crt ./private.key /app/
