FROM ghcr.io/zitadel/zitadel:v4.12.2@sha256:f65429aff8d0042d68c14007c69ae91914d4d73b368db48e54d4d77732efb272

# Add custom configuration and certificates
COPY --chown=zitadel:zitadel ./*.yaml ./certificate.crt ./private.key /app/
