name: Docker SBOM Staging

on:
  workflow_run:
    workflows: ["Docker build and push Staging"]
    types:
    - completed


env:
  AWS_REGION: ca-central-1
  REGISTRY_PREFIX: ${{ vars.STAGING_AWS_ACCOUNT_ID }}.dkr.ecr.ca-central-1.amazonaws.com

permissions:
  id-token: write
  contents: write
  
jobs:
  docker-sbom:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@f0796e7f3d6bec5d40aecb0321ed8012f5602f84
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
        DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
  
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
      with:
        role-to-assume: arn:aws:iam::${{ vars.STAGING_AWS_ACCOUNT_ID }}:role/unified-accounts-plan 
        role-session-name: PullImage
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@c962da2960ed15f492addc26fffa274485265950 # v2.0.2 

    - name: Generate Docker image SBOM
      uses: cds-snc/security-tools/.github/actions/generate-sbom@a55d3380441944245ba12aa93900ad062441df97
      env:
        TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
      with:
        docker_image: "${{ env.REGISTRY_PREFIX }}/idp:latest"
        dockerfile_path: "./docker/idp/Dockerfile"
        sbom_name: "idp"
        token: "${{ secrets.GITHUB_TOKEN }}"
        platform: "linux/arm64"
