name: Docker SBOM Staging

on:
  workflow_run:
    workflows: ["Docker build and push Staging"]
    types:
    - completed

permissions:
  contents: write
  
jobs:
  docker-sbom:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        image:
          - idp
          - idp-event-exporter
    
    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
        DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
        DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
        DNS_PROXY_WILDCARDGREEDY: "true"
  
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: changes
      with:
        filters: |
          docker:
            - './docker/${{ matrix.image }}/**'

    - name: Exit if no changes
      if: steps.changes.outputs.docker == 'false'
      run: exit 0

    - name: Build image
      run: |
        docker build \
          --platform linux/arm64 \
          --tag "${{ matrix.image }}:latest" \
          --file ./docker/${{ matrix.image }}/Dockerfile \
          ./docker/${{ matrix.image }}

    - name: Generate Docker image SBOM
      uses: cds-snc/security-tools/.github/actions/generate-sbom@837a88b6337d4842543184c8eac97a8adac8f302 # v4.0.3
      env:
        TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
      with:
        docker_image: "${{ matrix.image }}"
        dockerfile_path: "./docker/${{ matrix.image }}/Dockerfile"
        token: "${{ secrets.GITHUB_TOKEN }}"
        platform: "linux/arm64"