name: Docker SBOM Staging

on:
  workflow_run:
    workflows: ["Docker build and push Staging"]
    types:
    - completed


env: 
  REGISTRY_PREFIX: ${{ vars.STAGING_AWS_ACCOUNT_ID }}.dkr.ecr.ca-central-1.amazonaws.com

permissions:
  contents: write
  
jobs:
  docker-sbom:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        service:
          - idp
          - idp-login
    
    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@f0796e7f3d6bec5d40aecb0321ed8012f5602f84
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
        DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
  
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Build and push image
      run: |
        make cert
        docker buildx build \
          --platform linux/arm64 \
          -t "${{ env.REGISTRY_PREFIX }}/${{ matrix.service }}:latest" \
          -f ./docker/${{ matrix.service }}/Dockerfile \
          ./docker/${{ matrix.service }}

    - name: Generate Docker image SBOM
      uses: cds-snc/security-tools/.github/actions/generate-sbom@50aceef70baacb8b382e97e1ca7eaadc99ea94b6
      env:
        TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
      with:
        docker_image: "${{ env.REGISTRY_PREFIX }}/${{ matrix.service }}:latest"
        dockerfile_path: "./docker/${{ matrix.service }}/Dockerfile"
        sbom_name: "${{ matrix.service }}"
        token: "${{ secrets.GITHUB_TOKEN }}"
        platform: "linux/arm64"
