name: PR review get env vars

on:
  push:
    branches:
      - main
    paths:
      - "terraform/aws/**"
      - "terraform/env/**"
      - ".github/workflows/pr-review-get-vars.yml"
  workflow_dispatch:

env:
  AWS_REGION: ca-central-1

permissions:
  id-token: write
  contents: read

jobs:
  pr-review-get-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.STAGING_AWS_ACCOUNT_ID }}:role/platform-unified-accounts-pr-review-get-vars
          role-session-name: PRReviewGetEnvVars
          aws-region: ${{ env.AWS_REGION }}

      - name: Get environment variables
        env:
          CLUSTER_NAME: idp
          SERVICE_NAME: idp-login
        run: |
          .github/workflows/scripts/pr-review-get-vars.sh "$CLUSTER_NAME" "$SERVICE_NAME" > /dev/null 2>&1
