name: Terraform Drift Check Staging

concurrency:
  group: terraform-staging
  cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * MON-FRI'

env:
  AWS_REGION: ca-central-1
  TF_VAR_idp_admin_username: ${{ secrets.STAGING_IDP_ADMIN_USERNAME }}
  TF_VAR_idp_admin_password: ${{ secrets.STAGING_IDP_ADMIN_PASSWORD }}
  TF_VAR_cloudwatch_slack_webhook_url: ${{ secrets.STAGING_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}
  TF_VAR_idp_database_username: ${{ secrets.STAGING_IDP_DATABASE_USERNAME }}
  TF_VAR_idp_database_password: ${{ secrets.STAGING_IDP_DATABASE_PASSWORD }}
  TF_VAR_idp_database_admin_username: ${{ secrets.STAGING_IDP_DATABASE_ADMIN_USERNAME }}
  TF_VAR_idp_database_admin_password: ${{ secrets.STAGING_IDP_DATABASE_ADMIN_PASSWORD }}
  TF_VAR_idp_loginclient_machine_username: ${{ secrets.STAGING_IDP_LOGINCLIENT_MACHINE_USERNAME }}
  TF_VAR_idp_loginclient_pat: ${{ secrets.STAGING_IDP_LOGINCLIENT_PAT }}
  TF_VAR_idp_zitadel_org: ${{ secrets.STAGING_IDP_ZITADEL_ORG }}
  TF_VAR_idp_notify_api_key: ${{ secrets.STAGING_IDP_NOTIFY_API_KEY }}
  TF_VAR_idp_notify_template_id: ${{ secrets.STAGING_IDP_NOTIFY_TEMPLATE_ID }}
  TF_VAR_idp_secret_key: ${{ secrets.STAGING_IDP_SECRET_KEY }}
  TF_VAR_security_txt_content: ${{ vars.SECURITY_TXT_CDSSANDBOX_XYZ }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@f0796e7f3d6bec5d40aecb0321ed8012f5602f84 # v1.0.2
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.STAGING_AWS_ACCOUNT_ID }}:role/unified-accounts-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@36df0d7572a15921998170395475093c183d720a # v1.3.0
        env:
          CONFTEST_VERSION: NONE
          TERRAFORM_VERSION: 1.14.3
          TERRAFORM_CHECKSUM: 178b2a602251bb68b94732aceca2cc1023d87597cb83dba92cab31b6689edb4d
          TERRAGRUNT_VERSION: 0.98.0
          TERRAGRUNT_CHECKSUM: 68a9e029b438957c4164e505dfade123c67d6c3c3e11880bcadf3f2b33a8d865
          TF_SUMMARIZE_VERSION: NONE
          TRUFFLEHOG_VERSION: NONE

      - name: Check for drift
        working-directory: ./terraform/env/staging
        run: |
          terragrunt init
          terragrunt plan -detailed-exitcode