name: Workflow failure

on:
  workflow_call:
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID:
        required: true
      LOG_ANALYTICS_WORKSPACE_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

permissions:
  contents: none

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Notify Slack
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Unified Accounts workflow failed: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" "${{ secrets.SLACK_WEBHOOK_URL }}"